### ISSUE TITLE
Obvious statistical flaws.

### ISSUE THREAD

**Issue by pawelgalecki** [finsteininvest/pythonwilltrade#1]
Hi there, 

I don't speak German, not sure if I understood it right - but looking at the code there are some obvious errors in your rating methodology.

First of all - if a loan is issued a couple of days ago - it has no chance to be late - so LO who have issued a lot of loans recently can climb up the rating.
Also there are some LO who only have few loans - there's a good chance to have all of them current. Personally I would filter out all LO with less than 300 loans - they are statistically insignificant.

Obviously you realize that there's a lot more to rating LO than how their loans are paid.

**Comment by finsteininvest** [comment]
Thx for your comments. I will have a look at the data. Actually you pointed me in another direction. I will have closer look at LOs that issue a lot of loans in a short time period.

Yes you can extend rating in a lot of directions. My focus was not the rating - I wanted to check if it is possible to find the next defaulting LO. A high volume of overdue loans is alarming. At least for me.

I will be repeating the analysis in the future - maybe a trend can be found.
